version: '3.8'

services:
  # Banco de dados MySQL
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
    networks:
      - app-network

  # Aplicação PHP (3 instâncias)
  app1:
    build: ./app
    environment:
      - DB_HOST=db
    networks:
      - app-network
    depends_on:
      - db

  app2:
    build: ./app
    environment:
      - DB_HOST=db
    networks:
      - app-network
    depends_on:
      - db

  app3:
    build: ./app
    environment:
      - DB_HOST=db
    networks:
      - app-network
    depends_on:
      - db

  # Load Balancer Nginx
  nginx:
    build: ./nginx
    ports:
      - "8080:4500"
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
